apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
spec:
  selector:
    matchLabels:
      app: testdepapp
  replicas: 3
  template:
    metadata:
      labels:
        app: testdepapp
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
          - containerPort: 8000
