apiVersion: v1
kind: Pod
metadata:
  name: testapp
  labels:
    name: testapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
